environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"

init:
  - git config --global user.email dummy@example.org
  - git config --global user.name "Appveyor-C"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - npm run test-windows
